# Generated by Django 6.1 on 2026-08-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
